add Tips

diff --git a/.github/workflows/push.yaml b/.github/workflows/push.yaml
--- a/.github/workflows/push.yaml
+++ b/.github/workflows/push.yaml
@@ -22,8 +22,11 @@ jobs:
         while read line;do
           if [ ! -z $line ];then
             awk -F':' '{print $1,$2}'| while read IMAGE TAG;do
+             echo "push to ${REGISTRY}/${NAMESPACE}/${IMAGE}:${TAG}"
               docker tag $line ${REGISTRY}/${NAMESPACE}/${IMAGE}:${TAG}
-              docker push ${REGISTRY}/${NAMESPACE}/${IMAGE}:${TAG}
+              docker push ${REGISTRY}/${NAMESPACE}/${IMAGE}:${TAG}  && echo "push successful" || echo "push failure"
             done
+          else
+             echo "There is no image to push"
           fi
         done < image.txt 
